### ISSUE TITLE
Email spam when I starred paper_trail gem

### ISSUE THREAD

**Issue by mtimofiiv** [BemiHQ/bemi-rails#1]
![image](https://github.com/user-attachments/assets/34e79578-6786-4d2f-809d-02a93864e960)

Why did you send me this? This is clearly spam and you should be ashamed of yourselves.

**Comment by arjunlol** [comment]
@mtimofiiv that wasn't my intention, and we definitely don’t want to send anything that feels like spam. I'll close this out and not email you again. Thanks for flagging.
